version: '3'

services:
  web_app:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    image: quiz_vue:dev
    container_name: quiz_vue
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./:/usr/src/app
    command: 'yarn serve --port 3000'

networks:
  default:
    external:
      name: vue-learning-network